import FotoCristianoKruel from "../assets/palestrantes/cristiano-kruel.png";
import FotoWillianFarias from "../assets/palestrantes/willian-farias.png";
import FotoLeandroMazzola from "../assets/palestrantes/leandro-mazzola.png";
import FotoFelipePilau from "../assets/palestrantes/felipe-pilau.png";
import FotoCarlaWallauer from "../assets/palestrantes/carla-wallauer.png";
import FotoJoseMasiero from "../assets/palestrantes/jose-masiero.png";
import FotoZeRenato from "../assets/palestrantes/ze-renato.png";
import FotoPabloLorenzon from "../assets/palestrantes/pablo-lorenzon.png";
import FotoGabrielBaiao from "../assets/palestrantes/gabriel-baiao.png";
import FotoJulianoColombo from "../assets/palestrantes/juliano-colombo.png";
import FotoGabrielBorges from "../assets/palestrantes/gabriel-borges.png";
import FotoRodrigoPinto from "../assets/palestrantes/rodrigo-pinto.png";
import FotoClaudiaRocha from "../assets/palestrantes/claudia-rocha.png";
import FotoAngelinAdams from "../assets/palestrantes/angelin-adams.png";
import FotoPauloWalendorff from "../assets/palestrantes/paulo-walendorff.png";
import FotoGuilhermeNeves from "../assets/palestrantes/guilherme-neves.png";
import FotoGabrielMarkus from "../assets/palestrantes/gabriel-markus.png";
import FotoDietmarSukop from "../assets/palestrantes/dietmar-sukop.png";
import FotoAgustinLopez from "../assets/palestrantes/agustin-lopez.png";

import type { Palestrante } from "./Types";

export const palestrantes = [
  {
    nome: "Cristiano Kruel",
    cargo: "Chief Innovation Officer na StartSe",
    empresa: "StartSe",
    descricao:
      "Empreendedor, palestrante e mentor com mais de 30 anos de experiência em inovação, atuando em temas como tecnologias emergentes, disrupção, transformação de negócios, comportamento humano e governança. Coautor do livro Organizações Infinitas, pioneiro ao ter prefácio escrito por IA. Lifelong learner, desenvolveu programas focados em inteligência artificial para líderes empresariais. Atualmente é Chief Innovation Officer na StartSe, onde apoia grandes empresas em suas transformações e impulsiona startups em mercados desafiadores. ",
    foto: FotoCristianoKruel,
    painel: "Keynote Speaker",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "17h00 – 18h00",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "https://www.linkedin.com/in/cristianokruel/",
    instagram: "https://www.instagram.com/criskruel/",
    email: "",
  },

  {
    nome: "Willian Farias",
    cargo: "CEO e Cofundador",
    empresa: "4Feedstock",
    descricao:
      "CEO da 4Feedstock, empresa dedicada a impulsionar a economia circular por meio da valorização de resíduos industriais. Possui ampla experiência em inovação, estratégia e na construção de parcerias com startups, universidades e centros de P&D. Atua ativamente na promoção da neoindustrialização e na redução do envio de resíduos para aterros, fortalecendo a transição para um setor industrial mais sustentável. Sob sua liderança, a 4Feedstock vem conquistando grandes clientes globais e consolidando sua posição como referência internacional em economia circular até 2030, guiada por valores fundamentais como inovação, agilidade, sustentabilidade e transparência.",
    foto: FotoWillianFarias,
    painel: "Palco B | Inovar com Propósito",
    palcoDescricao: "Sustentabilidade e Resiliência Climática",
    bloco: "BLOCO 1 | ENTENDENDO O PRESENTE",
    horario: "14h - 15h",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "https://www.linkedin.com/in/willian-furtado-de-farias-junior/",
    instagram: "https://www.instagram.com/willianfarias_oficial/",
    email: "willianfariass@gmail.com",
  },
  {
    nome: "Leandro Mazzola",
    cargo: "Coordenador de Engenharia e P&E",
    empresa: "Coprel Telecom",
    descricao:
      "Coordenador de Engenharia de Telecomunicações da COPREL, onde atua desde 2004, com trajetória marcada por inovação e liderança técnica. Iniciou sua carreira na automação e supervisão de usinas, passando pela área de proteção e seletividade de energia e participando de projetos estratégicos, como as subestações de Passo Fundo e Ibirubá. Desde 2014 está na Coprel Telecom, onde estruturou a área de Gestão de Projetos e hoje lidera equipes de engenharia, planejamento, TI e novos serviços. Engenheiro Eletricista, é movido por tecnologia, robótica e transformação digital. Orgulha-se de ter contribuído diretamente para o crescimento da Telecom e acredita no poder da resiliência para superar desafios e gerar resultados sustentáveis.",
    foto: FotoLeandroMazzola,
    painel: "Palco A | O Agro do Amanhã",
    palcoDescricao: "Eficiência, Sustentabilidade e Conectividade",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "08h00 – 09h15",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "https://www.linkedin.com/in/leandro-mazzola/",
    instagram: "",
    email: "lmazzola@coprel.com.br",
  },
  {
    nome: "Felipe Pilau",
    cargo: "Prof. Dr. Departamento de Engenharia de Biossistemas",
    empresa: "ESALQ/USP",
    descricao:
      "Reconhecido como referência na interface entre climatologia agrícola e inovação tecnológica, atua em pesquisa, ensino e extensão. É engenheiro agrônomo formado pela Universidade Federal de Santa Maria (UFSM), onde também concluiu o mestrado em Agronomia. Doutor pela Escola Superior de Agricultura “Luiz de Queiroz” da Universidade de São Paulo (ESALQ/USP), exerce atualmente o cargo de professor associado no Departamento de Engenharia de Biossistemas da instituição. Com sólida experiência em ecofisiologia de culturas, micrometeorologia e modelagem agrometeorológica, desenvolve trabalhos que buscam aprimorar o manejo climático das culturas, reduzir riscos agrícolas e promover sistemas produtivos mais eficientes e sustentáveis.",
    foto: FotoFelipePilau,
    painel: "Palco B | Talks + Roda de Conversa | Inovar com Propósito",
    palcoDescricao: "Sustentabilidade e Resiliência Climática",
    bloco: "BLOCO 1 | ENTENDENDO O PRESENTE",
    horario: "14h - 15h",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Carla Wallauer",
    cargo: "Fundadora",
    empresa: "Boutique de Aromas",
    descricao:
      "Diretora e Cocriadora da Boutique de Aromas. Empreendedora e Cofundadora da marca Boutique de Aromas. Graduada em Farmácia e Bioquímica com MBA em gestão de empresas pela FGV. Minha jornada iniciou como empresária no segmento farmácia de manipulação em 1999 em Panambi com a franquia Vico Farma.",
    foto: FotoCarlaWallauer,
    painel: " Empreendendo Fora do Eixo",
    palcoDescricao: "Palco B | A Força das Iniciativas Locais",
    bloco: "BLOCO 3 | TRANSFORMANDO PESSOAS",
    horario: "09h45 – 11h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "https://www.linkedin.com/in/carla-wallauer-van-ass-58246325/",
    instagram: "https://www.instagram.com/carlavanass/",
    email: "",
  },
  {
    nome: "José Rodolfo Masiero",
    cargo: "Gerente de Inovação",
    empresa: "DBServer",
    descricao:
      "Profissional com mais de 15 anos de experiência em inovação, atualmente atuando como Gerente de Inovação Sênior na DB e fundador de 3 startups. Possui MBA em Inteligência, Estratégia e Inovação (ADM-UFRGS), Pós-Graduação em Ciência de Dados e Big Data (UniRitter) e graduação em Comunicação Social (UFRGS). Sua trajetória é marcada pela combinação de criatividade, empreendedorismo e conhecimento técnico para o desenvolvimento de soluções tecnológicas inovadoras para desafios de negócios.",
    foto: FotoJoseMasiero,
    painel: "Palco A  | Inteligência em Movimento: IA, Dados e Automação",
    palcoDescricao:
      "Transformações práticas no chão de fábrica com IA, gêmeos digitais, robotização e dados.",
    bloco: "BLOCO 1 | ENTENDENDO O PRESENTE",
    horario: "14h00 – 15h00",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Zé Renato",
    cargo: "Cofundador & CEO",
    empresa: "Raiô",
    descricao:
      "CEO da Raiô Benefícios e Presidente do South Summit Brazil. Liderou iniciativas empreendedoras nas áreas de tecnologia e experiência digital, cofundando empresas como Getnet e 4all.",
    foto: FotoZeRenato,
    painel: "Palco A | Marcas que Conectam",
    palcoDescricao: "O Cliente como Norte para Inovar e Crescer",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "15h30 – 16h30",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Pablo Lorenzon",
    cargo: "Gestor de Segurança da Informação",
    empresa: "Randoncorp",
    descricao:
      "Graduado em Ciência da Computação e com MBA em Gerenciamento de Projetos, atua nas áreas de Tecnologia e Segurança da Informação há 15 anos, incluindo passagens por segmentos econômicos distintos como Indústria Gráfica, Metal Mecânica, Construção Civil, Saúde, Educação e atualmente nos segmentos Automotivo e Financeiro. Também atua como mentor de Startups para novos negócios na Aceleradora Bluefields e no Centro de Inovação e Tecnologia de Erechim (CIT).",
    foto: FotoPabloLorenzon,
    painel: "Palco A  | Inteligência em Movimento: IA, Dados e Automação",
    palcoDescricao:
      "Transformações práticas no chão de fábrica com IA, gêmeos digitais, robotização e dados.",
    bloco: "BLOCO 1 | ENTENDENDO O PRESENTE",
    horario: "14h00 – 15h00",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Gabriel Baião Tavares",
    cargo: "Gerente de Operações Portuárias",
    empresa: "Portocel",
    descricao:
      "é gerente de Operações Portuárias da Portocel. Formado em Administração com habilitação em Comércio Exterior pela FDV, possui pós-graduação em Logística e Comércio Internacional, MBA em Gestão Financeira, Controladoria e Auditoria e curso de Gestão Portuária pelo Porto de Ghent, na Bélgica. Construiu sua trajetória profissional em Portocel, onde iniciou como estagiário, passando pelas áreas de Planejamento e Operação. Atuou também no Shipping e em projetos logísticos pela Fibria e Suzano. Ao longo de sua carreira, participou de missões técnicas e visitas a importantes portos internacionais, como Roterdã (Holanda), Antuérpia e Ghent (Bélgica), ampliando sua visão sobre eficiência e inovação na gestão portuária.",
    foto: FotoGabrielBaiao,
    painel: "Palco A  | Inteligência em Movimento: IA, Dados e Automação",
    palcoDescricao:
      "Transformações práticas no chão de fábrica com IA, gêmeos digitais, robotização e dados.",
    bloco: "BLOCO 1 | ENTENDENDO O PRESENTE",
    horario: "14h00 – 15h00",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Juliano Colombo",
    cargo: "Consultor, Investidor e Palestrante",
    empresa: "Juliano Colombo Consultoria e Treinamento Ltda",
    descricao:
      "É Pai, inquieto, transformador e acredita na liderança humanizada como forma de entregar resultados sustentáveis. Profissional com formação nas áreas de Gestão, Marketing e Finanças, com mais de 25 anos de experiência em gestão de equipes multidisciplinares e implantação de projetos de alto impacto nas áreas de saúde e educação. Liderou programas de inovação e transformação social, sendo por 10 anos Superintendente do SESI no Rio Grande do Sul. Atualmente é consultor, investidor, palestrante, membro de Conselhos de Entidades que atuam nas áreas de Educação e Inovação, como Parceiros Voluntários, Pacto pela Educação e diretor voluntário Na Fundação Projeto Pescar. Nos últimos anos tem se dedicado a conscientizar lideranças sobre os principais fatores que afetam o presente e o futuro do trabalho, transitando por temáticas como educação, saúde, cuidado, mulher, 50+ e liderança humanizada, sendo especialista em práticas ESG relacionadas a pessoas.",
    foto: FotoJulianoColombo,
    painel: "Palco A | Educação & Inovação",
    palcoDescricao: "Educação & Inovação: não existe atalho para o futuro",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "16h30 - 17h00",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Gabriel Borges",
    cargo: "Diretor de P&D",
    empresa: "SaveFarm Pulverização Seletiva",
    descricao: "",
    foto: FotoGabrielBorges,
    painel: "Palco A | O Agro do Amanhã",
    palcoDescricao: "Eficiência, Sustentabilidade e Conectividade",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "08h00 – 09h15",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Rodrigo Pinto Leis",
    cargo: "Sócio Consultor ",
    empresa: "PRODUTTARE",
    descricao: "",
    foto: FotoRodrigoPinto,
    painel: "Palco B | Inovação na Prática",
    palcoDescricao: "Lean, Ágil e Eficiência na Indústria",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "08h00 – 09h15",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Cláudia Rocha",
    cargo: "Referência em Transformações Organizacionais e Cultura Ágil",
    empresa: "-",
    descricao: "",
    foto: FotoClaudiaRocha,
    painel: "Palco B | Inovação na Prática",
    palcoDescricao: "Lean, Ágil e Eficiência na Indústria",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "08h00 – 09h15",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Angelin Adams",
    cargo: "CEO",
    empresa: "Saur",
    descricao: "",
    foto: FotoAngelinAdams,
    painel: "",
    palcoDescricao: "",
    bloco: "",
    horario: "16h30 - 17h00",
    dia: "",
    mes: "SETEMBRO",
    diaDaSemana: "8",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Paulo Walendorff",
    cargo: "Associate Director",
    empresa: "Evermonte Institute",
    descricao: "",
    foto: FotoPauloWalendorff,
    painel: "Palco A | Gente que Transforma",
    palcoDescricao: "Talentos, RH e Inclusão em Ambientes Inovadores",
    bloco: "TRANSFORMANDO PESSOAS",
    horario: "10h45 – 12h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Guilherme Neves",
    cargo: "Headhunter & Sócio",
    empresa: "Evermonte Executive Search",
    descricao: "",
    foto: FotoGuilhermeNeves,
    painel: "Palco A | Gente que Transforma",
    palcoDescricao: "Talentos, RH e Inclusão em Ambientes Inovadores",
    bloco: "TRANSFORMANDO PESSOAS",
    horario: "10h45 – 12h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Gabriel F. Markus",
    cargo: "Fundador",
    empresa: "WinStage ",
    descricao: "",
    foto: FotoGabrielMarkus,
    painel: "Palco B | Empreendendo Fora do Eixo",
    palcoDescricao: "A Força das Iniciativas Locais",
    bloco: "TRANSFORMANDO PESSOAS",
    horario: "10h45 – 12h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Dietmar Sukop",
    cargo: "Diretor Executivo",
    empresa: "Câmara Brasil-Alemanha de Porto Alegre",
    descricao: "",
    foto: FotoDietmarSukop,
    painel: " Visões do Futuro",
    palcoDescricao: "Tendências, Conexões e Novas Economias",
    bloco: "CONSTRUINDO O AMANHÃ",
    horario: "15h00 – 16h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Agustín López Munell",
    cargo: "CEO & Co-Founder",
    empresa: "Desitec S.A & CarbonXact Ltd.",
    descricao: "",
    foto: FotoAgustinLopez,
    painel: " Visões do Futuro",
    palcoDescricao: "Tendências, Conexões e Novas Economias",
    bloco: "CONSTRUINDO O AMANHÃ",
    horario: "15h00 – 16h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "",
    instagram: "",
    email: "",
  },
];

export function getPalestranteByNome(nome: string): Palestrante | undefined {
  return palestrantes.find(
    (p) => p.nome.trim().toLowerCase() === nome.trim().toLowerCase()
  );
}
