import FotoCristianoKruel from "../assets/palestrantes/cristiano-kruel.png";
import FotoWillianFarias from "../assets/palestrantes/willian-farias.png";
import FotoLeandroMazzola from "../assets/palestrantes/leandro-mazzola.png";
import FotoFelipePilau from "../assets/palestrantes/felipe-pilau.png";
import FotoCarlaWallauer from "../assets/palestrantes/carla-wallauer.png";
import FotoJoseMasiero from "../assets/palestrantes/jose-masiero.png";
import FotoZeRenato from "../assets/palestrantes/ze-renato.png";
import FotoPabloLorenzon from "../assets/palestrantes/pablo-lorenzon.png";
import FotoGabrielBaiao from "../assets/palestrantes/gabriel-baiao.png";
import FotoJulianoColombo from "../assets/palestrantes/juliano-colombo.png";
import FotoGabrielBorges from "../assets/palestrantes/gabriel-borges.png";
import FotoRodrigoPinto from "../assets/palestrantes/rodrigo-pinto.png";
import FotoClaudiaRocha from "../assets/palestrantes/claudia-rocha.png";
import FotoAngelinAdams from "../assets/palestrantes/angelin-adams.png";
import FotoPauloWalendorff from "../assets/palestrantes/paulo-walendorff.png";
import FotoGuilhermeNeves from "../assets/palestrantes/guilherme-neves.png";
import FotoGabrielMarkus from "../assets/palestrantes/gabriel-markus.png";
import FotoDietmarSukop from "../assets/palestrantes/dietmar-sukop.png";
import FotoAgustinLopez from "../assets/palestrantes/agustin-lopez.png";
import FotoSilvioCorrea from "../assets/palestrantes/silvio-correa.png";
import FotoFernandoFinger from "../assets/palestrantes/fernando-finger.png";
import FotoCleitonSilva from "../assets/palestrantes/cleiton-silva.png";
import FotoVaniaVerdasca from "../assets/palestrantes/vania-verdasca.png";
import FotoRaissaSchorn from "../assets/palestrantes/raissa-schorn.png";
import FotoMisiaraAlcantara from "../assets/palestrantes/misiara-alcantara.png";
import FotoGilianeTrost from "../assets/palestrantes/giliane-trost.png";
import FotoDiegoPiotto from "../assets/palestrantes/diego-piotto.png";
import FotoLuizDumoncel from "../assets/palestrantes/luiz-dumoncel.png";
import FotoMarcusRocha from "../assets/palestrantes/marcus-rocha.png";
import FotoAlexGranjeiro from "../assets/palestrantes/alex-granjeiro.png";
import FotoAndreLautert from "../assets/palestrantes/andre-lautert.png";
import FotoFelipeVieira from "../assets/palestrantes/felipe-vieira.png";
import FotoNicolasRossetto from "../assets/palestrantes/nicolas-rossetto.png";

import type { Palestrante } from "./Types";

export const palestrantes = [
  {
    nome: "Cristiano Kruel",
    cargo: "Chief Innovation Officer na StartSe",
    empresa: "StartSe",
    descricao:
      "Empreendedor, palestrante e mentor com mais de 30 anos de experiência em inovação, atuando em temas como tecnologias emergentes, disrupção, transformação de negócios, comportamento humano e governança. Coautor do livro Organizações Infinitas, pioneiro ao ter prefácio escrito por IA. Lifelong learner, desenvolveu programas focados em inteligência artificial para líderes empresariais. Atualmente é Chief Innovation Officer na StartSe, onde apoia grandes empresas em suas transformações e impulsiona startups em mercados desafiadores. ",
    foto: FotoCristianoKruel,
    painel: "Keynote Speaker",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "17h00 – 18h00",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "https://www.linkedin.com/in/cristianokruel/",
    instagram: "https://www.instagram.com/criskruel/",
    email: "",
  },

  {
    nome: "Willian Farias",
    cargo: "CEO e Cofundador",
    empresa: "4Feedstock",
    descricao:
      "CEO da 4Feedstock, empresa dedicada a impulsionar a economia circular por meio da valorização de resíduos industriais. Possui ampla experiência em inovação, estratégia e na construção de parcerias com startups, universidades e centros de P&D. Atua ativamente na promoção da neoindustrialização e na redução do envio de resíduos para aterros, fortalecendo a transição para um setor industrial mais sustentável. Sob sua liderança, a 4Feedstock vem conquistando grandes clientes globais e consolidando sua posição como referência internacional em economia circular até 2030, guiada por valores fundamentais como inovação, agilidade, sustentabilidade e transparência.",
    foto: FotoWillianFarias,
    painel: "Palco B | Inovar com Propósito:",
    palcoDescricao: "Sustentabilidade e Resiliência Climática",
    bloco: "BLOCO 1 | ENTENDENDO O PRESENTE",
    horario: "14h - 15h",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "https://www.linkedin.com/in/willian-furtado-de-farias-junior/",
    instagram: "https://www.instagram.com/willianfarias_oficial/",
    email: "willianfariass@gmail.com",
  },
  {
    nome: "Leandro Mazzola",
    cargo: "Coordenador de Engenharia e P&E",
    empresa: "Coprel Telecom",
    descricao:
      "Coordenador de Engenharia de Telecomunicações da COPREL, onde atua desde 2004, com trajetória marcada por inovação e liderança técnica. Iniciou sua carreira na automação e supervisão de usinas, passando pela área de proteção e seletividade de energia e participando de projetos estratégicos, como as subestações de Passo Fundo e Ibirubá. Desde 2014 está na Coprel Telecom, onde estruturou a área de Gestão de Projetos e hoje lidera equipes de engenharia, planejamento, TI e novos serviços. Engenheiro Eletricista, é movido por tecnologia, robótica e transformação digital. Orgulha-se de ter contribuído diretamente para o crescimento da Telecom e acredita no poder da resiliência para superar desafios e gerar resultados sustentáveis.",
    foto: FotoLeandroMazzola,
    painel: "Palco A | O Agro do Amanhã",
    palcoDescricao: "Eficiência, Sustentabilidade e Conectividade",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "08h00 – 09h15",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "https://www.linkedin.com/in/leandro-mazzola/",
    instagram: "",
    email: "lmazzola@coprel.com.br",
  },
  {
    nome: "Felipe Pilau",
    cargo: "Prof. Dr. Departamento de Engenharia de Biossistemas",
    empresa: "ESALQ/USP",
    descricao:
      "Reconhecido como referência na interface entre climatologia agrícola e inovação tecnológica, atua em pesquisa, ensino e extensão. É engenheiro agrônomo formado pela Universidade Federal de Santa Maria (UFSM), onde também concluiu o mestrado em Agronomia. Doutor pela Escola Superior de Agricultura “Luiz de Queiroz” da Universidade de São Paulo (ESALQ/USP), exerce atualmente o cargo de professor associado no Departamento de Engenharia de Biossistemas da instituição. Com sólida experiência em ecofisiologia de culturas, micrometeorologia e modelagem agrometeorológica, desenvolve trabalhos que buscam aprimorar o manejo climático das culturas, reduzir riscos agrícolas e promover sistemas produtivos mais eficientes e sustentáveis.",
    foto: FotoFelipePilau,
    painel: "Palco B | Talks + Roda de Conversa | Inovar com Propósito",
    palcoDescricao: "Sustentabilidade e Resiliência Climática",
    bloco: "BLOCO 1 | ENTENDENDO O PRESENTE",
    horario: "14h - 15h",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "linkedin.com/in/felipe-pilau-a7266030",
    instagram: "",
    email: "",
  },
  {
    nome: "Carla Wallauer",
    cargo: "Fundadora",
    empresa: "Boutique de Aromas",
    descricao:
      "Diretora e Cocriadora da Boutique de Aromas. Empreendedora e Cofundadora da marca Boutique de Aromas. Graduada em Farmácia e Bioquímica com MBA em gestão de empresas pela FGV. Minha jornada iniciou como empresária no segmento farmácia de manipulação em 1999 em Panambi com a franquia Vico Farma.",
    foto: FotoCarlaWallauer,
    painel: " Empreendendo Fora do Eixo",
    palcoDescricao: "Palco B | A Força das Iniciativas Locais",
    bloco: "BLOCO 3 | BLOCO 3 | TRANSFORMANDO PESSOAS",
    horario: "09h45 – 11h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "https://www.linkedin.com/in/carla-wallauer-van-ass-58246325/",
    instagram: "https://www.instagram.com/carlavanass/",
    email: "",
  },
  {
    nome: "José Rodolfo Masiero",
    cargo: "Gerente de Inovação",
    empresa: "DBServer",
    descricao:
      "Profissional com mais de 15 anos de experiência em inovação, atualmente atuando como Gerente de Inovação Sênior na DB e fundador de 3 startups. Possui MBA em Inteligência, Estratégia e Inovação (ADM-UFRGS), Pós-Graduação em Ciência de Dados e Big Data (UniRitter) e graduação em Comunicação Social (UFRGS). Sua trajetória é marcada pela combinação de criatividade, empreendedorismo e conhecimento técnico para o desenvolvimento de soluções tecnológicas inovadoras para desafios de negócios.",
    foto: FotoJoseMasiero,
    painel: "Palco A  | Inteligência em Movimento: IA, Dados e Automação",
    palcoDescricao:
      "Transformações práticas no chão de fábrica com IA, gêmeos digitais, robotização e dados.",
    bloco: "BLOCO 1 | ENTENDENDO O PRESENTE",
    horario: "14h00 – 15h00",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "linkedin.com/in/jrmasiero",
    instagram: "",
    email: "jrmasiero@gmail.com",
  },
  {
    nome: "Zé Renato",
    cargo: "Cofundador & CEO",
    empresa: "Raiô",
    descricao:
      "CEO da Raiô Benefícios e Presidente do South Summit Brazil. Liderou iniciativas empreendedoras nas áreas de tecnologia e experiência digital, cofundando empresas como Getnet e 4all.",
    foto: FotoZeRenato,
    painel: "Palco A | Marcas que Conectam",
    palcoDescricao: "O Cliente como Norte para Inovar e Crescer",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "15h30 – 16h30",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "linkedin.com/in/jose-renato-hopf-raiô",
    instagram: "https://www.instagram.com/zecahopf/",
    email: "",
  },
  {
    nome: "Pablo Lorenzon",
    cargo: "Gestor de Segurança da Informação",
    empresa: "Randoncorp",
    descricao:
      "Graduado em Ciência da Computação e com MBA em Gerenciamento de Projetos, atua nas áreas de Tecnologia e Segurança da Informação há 15 anos, incluindo passagens por segmentos econômicos distintos como Indústria Gráfica, Metal Mecânica, Construção Civil, Saúde, Educação e atualmente nos segmentos Automotivo e Financeiro. Também atua como mentor de Startups para novos negócios na Aceleradora Bluefields e no Centro de Inovação e Tecnologia de Erechim (CIT).",
    foto: FotoPabloLorenzon,
    painel: "Palco A  | Inteligência em Movimento: IA, Dados e Automação",
    palcoDescricao:
      "Transformações práticas no chão de fábrica com IA, gêmeos digitais, robotização e dados.",
    bloco: "BLOCO 1 | ENTENDENDO O PRESENTE",
    horario: "14h00 – 15h00",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "linkedin.com/in/pablo-lorenzon",
    instagram: "",
    email: "",
  },
  {
    nome: "Gabriel Baião Tavares",
    cargo: "Gerente de Operações Portuárias",
    empresa: "Portocel",
    descricao:
      "é gerente de Operações Portuárias da Portocel. Formado em Administração com habilitação em Comércio Exterior pela FDV, possui pós-graduação em Logística e Comércio Internacional, MBA em Gestão Financeira, Controladoria e Auditoria e curso de Gestão Portuária pelo Porto de Ghent, na Bélgica. Construiu sua trajetória profissional em Portocel, onde iniciou como estagiário, passando pelas áreas de Planejamento e Operação. Atuou também no Shipping e em projetos logísticos pela Fibria e Suzano. Ao longo de sua carreira, participou de missões técnicas e visitas a importantes portos internacionais, como Roterdã (Holanda), Antuérpia e Ghent (Bélgica), ampliando sua visão sobre eficiência e inovação na gestão portuária.",
    foto: FotoGabrielBaiao,
    painel: "Palco A  | Inteligência em Movimento: IA, Dados e Automação",
    palcoDescricao:
      "Transformações práticas no chão de fábrica com IA, gêmeos digitais, robotização e dados.",
    bloco: "BLOCO 1 | ENTENDENDO O PRESENTE",
    horario: "14h00 – 15h00",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "",
    instagram: "",
    email: "",
  },
  {
    nome: "Juliano Colombo",
    cargo: "Consultor, Investidor e Palestrante",
    empresa: "Juliano Colombo Consultoria e Treinamento Ltda",
    descricao:
      "É pai, inquieto e transformador, acreditando que a liderança humanizada é o caminho para resultados verdadeiramente sustentáveis. Formado em Gestão, Marketing e Finanças, reúne mais de 25 anos de experiência conduzindo equipes multidisciplinares e implantando projetos de alto impacto nas áreas de saúde e educação. Foi responsável por liderar programas de inovação e transformação social, atuando por uma década como Superintendente do SESI no Rio Grande do Sul. Hoje atua como consultor, investidor e palestrante, além de integrar conselhos de entidades ligadas à Educação e à Inovação, como Parceiros Voluntários, Pacto pela Educação e a Fundação Projeto Pescar, onde exerce a função de diretor voluntário. Nos últimos anos, tem se dedicado a despertar lideranças para os principais fatores que impactam o presente e o futuro do trabalho, transitando por temas como educação, saúde, cuidado, equidade de gênero, longevidade (50+) e liderança humanizada. É também especialista em práticas ESG voltadas para pessoas, reforçando sua missão de conectar propósito, impacto social e resultados de longo prazo.",
    foto: FotoJulianoColombo,
    painel: "Palco A | Educação & Inovação:",
    palcoDescricao: "Educação & Inovação: não existe atalho para o futuro",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "16h30 - 17h00",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "linkedin.com/in/julianoacolombo",
    instagram: "https://www.instagram.com/julianoacolombo/",
    email: "julianoacolombo@gmail.com",
  },
  {
    nome: "Gabriel Borges",
    cargo: "Diretor de P&D",
    empresa: "SaveFarm Pulverização Seletiva",
    descricao:
      "Engenheiro Eletricista com Mestrado em Engenharia Elétrica pela Universidade Federal do Rio Grande do Sul (UFRGS), com foco em Inteligência Artificial. Cofundador e Diretor de Pesquisa e Desenvolvimento da Eirene Solutions, empresa que desenvolve soluções de visão computacional e automação para o setor agrícola.",
    foto: FotoGabrielBorges,
    painel: "Palco A | O Agro do Amanhã:",
    palcoDescricao: "Eficiência, Sustentabilidade e Conectividade",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "08h00 – 09h15",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "https://www.linkedin.com/in/gabriel-borges-53a71325/",
    instagram: "",
    email: "",
  },
  {
    nome: "Rodrigo Pinto Leis",
    cargo: "Sócio Consultor ",
    empresa: "PRODUTTARE",
    descricao:
      "Atua como consultor técnico, sendo um dos principais nomes brasileiros na aplicação e difusão de Sistemas de Produção Enxuta, Engenharia Simultânea, Gestão Visual e Estruturação de Operações Industriais. Com doutorado pela UFRGS, atua como pesquisador e consultor sênior na Produttare, levando inovação de processo a empresas como AGCO, Stara, Randon, Dana e Taurus. É autor e coautor de publicações e artigos científicos relevantes, com produção técnico-acadêmica associada à integração entre Lean, desenvolvimento de produtos e estratégia operacional, sempre com uma abordagem realista, pragmática e voltada à aplicação direta em chão de fábrica.",
    foto: FotoRodrigoPinto,
    painel: "Palco B | Inovação na Prática:",
    palcoDescricao: "Lean, Ágil e Eficiência na Indústria",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "08h00 – 09h15",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "https://www.linkedin.com/in/rodrigo-pinto-leis-a2aaa4/",
    instagram: "",
    email: "",
  },
  {
    nome: "Cláudia Rocha",
    cargo: "Referência em Transformações Organizacionais e Cultura Ágil",
    empresa: "",
    descricao:
      "É apaixonada por transformações organizacionais e digitais, desenvolvimento humano, agilidade e tecnologia. Adora interagir com pessoas, compartilhar conhecimento e está constantemente aprendendo. Com mais de 20 anos de experiência em transformações, implementou metodologias que resultaram em transições sustentáveis. Sua experiência inclui a facilitação de workshops, mentoria de líderes e equipes, e a implementação de frameworks e metodologias, sempre focando na melhoria de processos, na agilidade e no desenvolvimento de pessoas. Possui vivência em ambientes complexos (IBM, Lojas Renner S.A., PUCRS) e no gerenciamento de projetos de transformação. Graduada em Tecnólogo em Processamento de Dados pela Unisinos, e pós-graduada em “Desenvolvimento de Sistemas de Informação” e “Gestão Empresarial” pela UFRGS, em “Melhoria do Processo de Software” pela UFLA, e em “Psicologia Positiva: Ciência do Bem-Estar e Autorrealização” pela PUCRS.",
    foto: FotoClaudiaRocha,
    painel: "Palco B | Inovação na Prática:",
    palcoDescricao: "Lean, Ágil e Eficiência na Indústria",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "08h00 – 09h15",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "linkedin.com/in/claudiarsrocha",
    instagram: "",
    email: "",
  },
  {
    nome: "Angelin Adams",
    cargo: "CEO",
    empresa: "Saur",
    descricao:
      "CEO da SAUR Equipamentos S.A. e Presidente do Instituto Agregar. Iniciou sua trajetória em 1991 como jovem aprendiz, quando também cursou o técnico em Mecânica. É graduado em Engenharia Mecânica pela Unijuí e possui MBAs em Gestão Empresarial e em Gestão Financeira pela FGV. Ao longo de sua carreira, atuou nas áreas de engenharia e comercial, foi gestor da ferramentaria e ocupou a posição de CEO da Bruning Tecnometal.",
    foto: FotoAngelinAdams,
    painel: "Palco A | Educação & Inovação:",
    palcoDescricao: "Não Existe Atalho Para o Futuro",
    bloco: "",
    horario: "16h30 - 17h00",
    dia: "",
    mes: "SETEMBRO",
    diaDaSemana: "8",
    linkedin: "linkedin.com/in/angelin-adams-34980a10",
    instagram: "",
    email: "",
  },
  {
    nome: "Paulo Walendorff",
    cargo: "Associate Director",
    empresa: "Evermonte Institute",
    descricao:
      "Associate Director do Evermonte Institute, construiu sua carreira em empresas de auditoria (Big Four), indústria de bens de capital, tecnologia e serviços financeiros, consolidando-se como um dos principais líderes executivos de RH no Sul do Brasil. Atualmente, lidera as operações do Evermonte Institute e atua como professor na PUCRS.",
    foto: FotoPauloWalendorff,
    painel: "Palco A | Gente que Transforma:",
    palcoDescricao: "Talentos, RH e Inclusão em Ambientes Inovadores",
    bloco: "BLOCO 3 | TRANSFORMANDO PESSOAS",
    horario: "10h45 – 12h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "linkedin.com/in/paulowalendorff",
    instagram: "https://www.instagram.com/paulowalendorff/",
    email: "",
  },
  {
    nome: "Guilherme Neves",
    cargo: "Headhunter & Sócio",
    empresa: "Evermonte Executive Search",
    descricao:
      "Sócio da Evermonte Executive Search, trilhou seu caminho no mercado de recrutamento executivo através de uma consultoria multinacional, expandindo sua experiência em uma indústria multinacional de grande porte. Ao longo de sua carreira, Guilherme tem desempenhado um papel crucial ao auxiliar líderes de empresas a recrutar altos executivos, contribuindo para processos de profissionalização e crescimento. Além de suas responsabilidades como Sócio, Guilherme lidera a área de People Analytics e Psicometria Avançada Evermonte.",
    foto: FotoGuilhermeNeves,
    painel: "Palco A | Gente que Transforma:",
    palcoDescricao: "Talentos, RH e Inclusão em Ambientes Inovadores",
    bloco: "BLOCO 3 | TRANSFORMANDO PESSOAS",
    horario: "10h45 – 12h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "https://www.linkedin.com/in/guilherme-neves-headhunter/",
    instagram: "",
    email: "",
  },
  {
    nome: "Gabriel F. Markus",
    cargo: "Fundador",
    empresa: "WinStage ",
    descricao:
      " Empresário de 23 anos, fundador da WinStage - marca líder em barras de proteína naturais no Brasil, presente em mais de 2.000 pontos de venda e referência em inovação no setor de alimentos saudáveis.",
    foto: FotoGabrielMarkus,
    painel: "Palco B | Empreendendo Fora do Eixo:",
    palcoDescricao: "A Força das Iniciativas Locais",
    bloco: "BLOCO 3 | TRANSFORMANDO PESSOAS",
    horario: "10h45 – 12h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "https://www.linkedin.com/in/gabriel-markus/",
    instagram: "",
    email: "gabriel@winstage.com.br",
  },
  {
    nome: "Dietmar Sukop",
    cargo: "Diretor Executivo",
    empresa: "Câmara Brasil-Alemanha de Porto Alegre",
    descricao:
      "Alemão, formado em geologia na Alemanha, com especialização em economia empresarial pela UFRGS, desde 2002 na Câmara Brasil-Alemanha trabalhando no fomento econômico entre Brasil (com foco no RS) e Alemanha. Inicialmente como coordenador de projetos, depois liderando a área de comércio exterior e diretor executivo adjunto com atuação na organização de delegações e feiras, elaboração de estudos de mercado e trabalhando na intermediação de negócios. Desde 2018 na frente da Câmara Brasil-Alemanha como diretor executivo.",
    foto: FotoDietmarSukop,
    painel: "Visões do Futuro:",
    palcoDescricao: "Tendências, Conexões e Novas Economias",
    bloco: "CONSTRUINDO O AMANHÃ",
    horario: "15h00 – 16h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "https://www.linkedin.com/in/dietmar-sukop-1a698b20/",
    instagram: "",
    email: "dietmar.sukop@ahkrs.com.br",
  },
  {
    nome: "Agustín López Munell",
    cargo: "CEO & Co-Founder",
    empresa: "Desitec S.A & CarbonXact Ltd.",
    descricao: "",
    foto: FotoAgustinLopez,
    painel: " Visões do Futuro",
    palcoDescricao: "Tendências, Conexões e Novas Economias",
    bloco: "CONSTRUINDO O AMANHÃ",
    horario: "15h00 – 16h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "https://www.linkedin.com/in/agustin-lopez-munell-517439142/",
    instagram: "",
    email: "",
  },
  {
    nome: "Sílvio Corrêa",
    cargo: "CEO & Co-Founder",
    empresa: "Easypro Tecnologia",
    descricao: "",
    foto: FotoSilvioCorrea,
    painel: "Palco B | Arena de Tecnologia:",
    palcoDescricao: "Inovação em Ação",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "15h30 – 16h30",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "https://www.linkedin.com/in/silvio-correa-5b755244/",
    instagram: "",
    email: "silvio@easypro.com.br",
  },
  {
    nome: "Fernando Finger",
    cargo: " Sócio Proprietário e Diretor",
    empresa: "Tecnofinger Eletrônica e Equipamentos",
    descricao: "",
    foto: FotoFernandoFinger,
    painel: "Palco B | Arena de Tecnologia:",
    palcoDescricao: "Inovação em Ação",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "15h30 – 16h30",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "https://www.linkedin.com/in/fernando-henrique-finger-340441133/",
    instagram: "",
    email: "",
  },
  {
    nome: "Cleiton Silva",
    cargo: " Diretor de Engenharia, Tecnologia & Equipamentos Eletrônicos",
    empresa: "EMBRAER",
    descricao:
      "É engenheiro eletrônico graduado pelo Instituto Tecnológico de Aeronáutica (ITA) em 2002, com distinção summa cum laude. Possui mestrado (2004) e doutorado (2008) em Sistemas e Controle pela mesma instituição, além de MBA em Gestão Estratégica de Pessoas pela FGV (2015) e especialização em Administração Estratégica pela FIA (2025). Desde 2006 atua na Embraer, onde teve papel central no desenvolvimento das leis de controle FBW/AFCS de aeronaves como E1, Phenom 100, Phenom 300, Legacy 500 e C-390. Foi Gerente de Desenvolvimento de Produto do C-390, liderou o desenvolvimento de novos produtos na aviação comercial e, desde 2023, ocupa o cargo de Diretor de Tecnologia e Equipamentos Eletrônicos. Também integra o Conselho Consultivo da ATECH (desde jun/2023) e o Conselho de Administração da VISIONA (desde ago/2024).",
    foto: FotoCleitonSilva,
    painel: "Palco A | Inovação na EMBRAER:",
    palcoDescricao: "de tendências a resultados",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "08h00 - 09h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "https://www.linkedin.com/in/cleiton-silva-38611915/",
    instagram: "",
    email: "cleitonsilva@gmail.com",
  },
  {
    nome: "Vânia Verdasca",
    cargo: "Gerente de Qualidade e Melhoria Contínua",
    empresa: "KeplerWeber",
    descricao:
      "Farmacêutica Industrial, Especialista em Sistemas de Gestão da Qualidade, Black Belt em Lean Seis Sigma, mais de 20 anos de experiência em Qualidade, Produção e Gestão Integrada, com forte atuação em empresas nacionais e multinacionais dos setores farmacêutico, químico, cosmético e agronegócio. Vivência em implantação de sistemas de gestão e melhoria contínua, com domínio de ferramentas Lean, Six Sigma e WCM. Gerente em projetos de licenciamento industrial e certificações (ANVISA, MAPA, ISO, BPF), transferência de site e implantação de sistemas BPMS.",
    foto: FotoVaniaVerdasca,
    painel:
      "Palco B | Inovação na Prática: Lean, Ágil e Eficiência na Indústria",
    palcoDescricao:
      "Métodos e ferramentas para inovar com poucos recursos e alto impacto.",
    bloco: "BLOCO 2 | RESOLVENDO O AGORA",
    horario: "09h00 – 10h15",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "linkedin.com/in/vania-andrade1",
    instagram: "",
    email: "",
  },
  {
    nome: "Raíssa Schorn",
    cargo: "Vice-diretora Nacional",
    empresa: "Rede Internacional de Promotores dos ODS",
    descricao:
      "É cofundadora da Projetou Captação de Recursos,  e atua como vice-diretora nacional da Rede Internacional de Promotores dos ODS (RIPO Brasil). Doutoranda em Desenvolvimento Regional (UNIJUÍ) com estágio de pesquisa em Portugal (UTAD), atua na área de cidades inteligentes e inovação com foco no desenvolvimento urbano e sustentável.",
    foto: FotoRaissaSchorn,
    painel:
      "Palco B | Roda de Conversa | Cidades Inteligentes, Inclusivas e Digitais",
    palcoDescricao: "",
    bloco: "BLOCO 4 | CONSTRUINDO O AMANHÃ: Conexões e futuros desejados",
    horario: "13h30 – 14h30",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "linkedin.com/in/raíssa-schorn-68b7821b5",
    instagram: "",
    email: "",
  },
  {
    nome: "Misiara De Alcântara",
    cargo: "Diretora de Recursos Humanos",
    empresa: "3tentos",
    descricao:
      "Diretora de Recursos Humanos da 3tentos, Conselheira da ABRH-RS, foi Diretora de Gente&Gestão da Kepler Weber. Formada em administração de Empresas, com especialização em Gestão de Pessoas na FGV e mestre em Administração pela UFRGS.",
    foto: FotoGilianeTrost,
    painel:
      "Palco A | Gente que Transforma: Talentos, RH   e Inclusão em Ambientes Inovadores",
    palcoDescricao:
      "Soluções para recrutamento, formação e engajamento de talentos nos territórios.",
    bloco: "BLOCO 3 | TRANSFORMANDO PESSOAS: Inovação é feita de gente",
    horario: "10h45 – 12h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "linkedin.com/in/misiara-de-alcântara-b6366025",
    instagram: "",
    email: "misiaradealcantara@gmail.com",
  },
  {
    nome: "Giliane Trost",
    cargo: "CEO",
    empresa: "Tromink",
    descricao:
      "Empresária e sócia da Tromink Industrial Ltda, atua como CEO da companhia, referência na fabricação de equipamentos para unidades armazenadoras de grãos e sistemista de componentes soldados para montadoras agrícolas. Graduada em Administração de Empresas, com MBA em Gestão de Pessoas e Estratégia Empresarial pela FGV e Mestrado em Administração pela UFRGS, iniciou sua trajetória na Tromink em 1993 como auxiliar administrativa e, ao longo de mais de três décadas, acompanhou e impulsionou o crescimento da empresa, consolidando-se como liderança estratégica que hoje está à frente da organização.",
    foto: FotoMisiaraAlcantara,
    painel:
      "Palco B | Empreendendo Fora do Eixo: A Força das Iniciativas Locais",
    palcoDescricao:
      "Casos de sucesso de startups e empreendedores que inovam fora dos grandes centros. ",
    bloco: "BLOCO 3 | TRANSFORMANDO PESSOAS: Inovação é feita de gente",
    horario: "10h45 – 12h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "linkedin.com/in/giliane-brandt-a12988bb",
    instagram: "",
    email: "giliane@tromink.com.br",
  },
  {
    nome: "Diego Piotto",
    cargo: "Gerente Executivo de Engenharia",
    empresa: "Soli3",
    descricao:
      "Engenheiro eletricista com MBA em gerenciamento de projetos e Mestrado em Finanças pela FGV. Certificação PMP pelo PMI. Com 18 anos de experiência em projetos industriais de grande porte com passagens pela Amaggi, Etamil Bioenergia e Uisa. Experiência em projetos industriais, excelência operacional , lean manufacturing e operações industriais.",
    foto: FotoDiegoPiotto,
    painel:
      "Palco A | Energia Verde: Inovação e Sustentabilidade nos Combustíveis do Futuro",
    palcoDescricao: "",
    bloco: "BLOCO 4 | CONSTRUINDO O AMANHÃ: Conexões e futuros desejados",
    horario: "13h30 – 14h30",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "linkedin.com/in/diego-piotto-pmp®-msc-3736913b",
    instagram: "",
    email: "dpiotto@gmail.com",
  },
  {
    nome: "Luiz Dumoncel",
    cargo: "Diretor Vice-Presidente de Operações",
    empresa: "3tentos",
    descricao:
      "Graduado em Administração pela PUCRS com Especialização em Gestão de Negócios pela Fundação Dom Cabral. Também participou do Curso Hectare – Gestão e Sucessão Rural promovido Perestroika – POA. Iniciou suas atividades profissionais como estagiário no Banco do Brasil. Após, atuou como trainee na INTL FCStone Inc. (Estados Unidos) no setor de gerenciamento de risco de commodities agrícolas e de importação de café e cacau. Em 2014, ingressou no Programa de Trainee para Sucessores na 3tentos Agroindustrial e foi Gerente de Fertilizantes dentro da empresa entre 2017 e 2020, período em que o setor cresceu 213% em vendas. Ele atuou como Diretor de Commodities entre 2021 e 2025, ano em que assumiu o cargo atual de Diretor Vice-Presidente de Operações (COO).",
    foto: FotoLuizDumoncel,
    painel:
      "Palco A | Energia Verde: Inovação e Sustentabilidade nos Combustíveis do Futuro",
    palcoDescricao: "",
    bloco: "BLOCO 4 | CONSTRUINDO O AMANHÃ: Conexões e futuros desejados",
    horario: "13h30 – 14h30",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "linkedin.com/in/luiz-dumoncel-2a520079",
    instagram: "",
    email: "",
  },
  {
    nome: "Marcus Rocha",
    cargo: "Diretor de Operações",
    empresa: "LifesHub",
    descricao:
      "É empreendedor, consultor e professor com ampla internacional na gestão estratégica da inovação tecnológica. Conselheiro da Associação Empresarial de Florianópolis (Acif) e do Conselho Municipal de Inovação, é CEO da consultoria ION Ideias On e COO da LifesHub, além de atuar na Coordenação do Programa Florianópolis Cidade Criativa Unesco. De 2017 a 2021 foi Superintendente de Ciência, Tecnologia e Inovação na Prefeitura Municipal de Florianópolis, quando foi responsável pela implantação da pioneira Lei Municipal de Inovação, da Rede Municipal de Centros de Inovação e do Living Lab Florianópolis. Mestre e MBA em Gestão da Inovação, é autor do livro 'Territórios da Inovação', uma obra inédita da literatura corporativa brasileira sobre o desenvolvimento de ecossistemas de inovação.",
    foto: FotoMarcusRocha,
    painel:
      "Palco B | Roda de Conversa | Cidades Inteligentes, Inclusivas e Digitais",
    palcoDescricao: "",
    bloco: "BLOCO 4 | CONSTRUINDO O AMANHÃ: Conexões e futuros desejados",
    horario: "13h30 – 14h30",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "linkedin.com/in/rochamarcus",
    instagram: "https://www.instagram.com/marcusroc/",
    email: "marcusjoserocha@gmail.com",
  },
  {
    nome: "Alex Granjeiro",
    cargo: "Innovation Partner",
    empresa: "Claro Brasil",
    descricao:
      "É um especialista em inovação do beOn, com um olhar focado em Open Innovation e Transformação Digital. Com profunda expertise em Metodologias Ágeis e Gestão de Projetos, ele se destaca na implantação e desenvolvimento de aceleradoras e programas de aceleração, além de programas de inovação corporativa e intraempreendedorismo.",
    foto: FotoAlexGranjeiro,
    painel:
      "Palco B | Roda de Conversa | Cidades Inteligentes, Inclusivas e Digitais",
    palcoDescricao: "",
    bloco: "BLOCO 4 | CONSTRUINDO O AMANHÃ: Conexões e futuros desejados",
    horario: "13h30 – 14h30",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "linkedin.com/in/alex-granjeiro-6432b343",
    instagram: "",
    email: "",
  },
  {
    nome: "André Lautert",
    cargo: "CFO",
    empresa: "Fockink",
    descricao:
      "CFO da Fockink, profissional com 29 anos de experiência atuando em auditoria, consultoria, contabilidade, controladoria, fiscal, recursos humanos, jurídico e TI em empresas nacionais e multinacionais nos segmentos de indústrias, varejo e serviços.",
    foto: FotoAndreLautert,
    painel:
      "Palco A |  Visões do Futuro: Tendências, Conexões e Novas Economias",
    palcoDescricao:
      "Debate inspirador com especialistas sobre futuros possíveis, novas economias e o papel da região no cenário global",
    bloco: "BLOCO 4 | CONSTRUINDO O AMANHÃ: Conexões e futuros desejados",
    horario: "16h00 – 17h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "linkedin.com/in/andre-lautert-48308846",
    instagram: "",
    email: "lautertandre@gmail.com",
  },
  {
    nome: "Felipe Vieira",
    cargo: "Co-founder",
    empresa: "Raízes Corretora de Seguros",
    descricao:
      "Engenheiro florestal pela UFPR, com especialização em marketing pela FGV de SP e MBA executivo pela FAE Business School. Educação executiva em gestão de canais de distribuição pela Kellogg Northwester University Chicago, e Liderança e Negociação pela Harvard Law School e Fusões e Aquisições pela COlumbia de Nova York.20 anos de experiência executiva com cargos de liderança na américa latina nas áreas comercial, marketing, estratégia e gestão de empresa no segmento de máquinas florestais, agrícolas e de construção, com passagem por empresas como John Deere, CNH, Komatsu, Valley e Paraná Equipamentos (Caterpillar). Atualmente sócio da AGROBRAVO enterprises, Socio fundador da Raízes corretora de Seguros e membro do conselho do grupo Grão de Ouro.",
    foto: FotoFelipeVieira,
    painel:
      "Palco A | As conexões movem o mundo. Um olhar à inovação e desenvolvimento de novos negócios além do barulho da mídia",
    palcoDescricao: "",
    bloco: "BLOCO 4 | CONSTRUINDO O AMANHÃ: Conexões e futuros desejados",
    horario: "17h00 – 18h00",
    dia: "09",
    mes: "SETEMBRO",
    diaDaSemana: "TERÇA",
    linkedin: "linkedin.com/in/felipe-vieira-565b6b18",
    instagram: "",
    email: "",
  },
  {
    nome: "Nicolas Rossetto",
    cargo: "HEAD of Application Engineering Team",
    empresa: "SKA",
    descricao:
      "Engenheiro Industrial Mecânico com mais de 20 anos de experiência, iniciou sua jornada com as soluções SOLIDWORKS em 2005. Atuou em diferentes segmentos industriais, incluindo engenharia térmica, máquinas e equipamentos e construção civil, com vivência em engenharia reversa, manufatura aditiva (impressão 3D), simulação por elementos finitos e renderização. Na SKA, passou por diversas posições — de suporte técnico e implantação a engenheiro de aplicações — sendo responsável por validações técnicas do SOLIDWORKS junto a clientes de diferentes portes e setores. Já liderou equipes de implantação e engenharia de aplicações e, atualmente, é Head de Comunicação Técnica, conduzindo times focados na criação de conteúdo estratégico para os produtos Dassault Systèmes.",
    foto: FotoNicolasRossetto,
    painel:
      "Palco B | Talks + Roda de Conversa | Inovar com Propósito: Sustentabilidade e Resiliência Climática",
    palcoDescricao:
      "Soluções sustentáveis para prevenir desastres, otimizar recursos e inovar com impacto positivo.",
    bloco: "BLOCO 1 | ENTENDENDO O PRESENTE: O mundo já mudou",
    horario: "14h00 – 15h00",
    dia: "08",
    mes: "SETEMBRO",
    diaDaSemana: "SEGUNDA",
    linkedin: "linkedin.com/in/nicolasrossetto",
    instagram: "",
    email: "",
  },
];

export function getPalestranteByNome(nome: string): Palestrante | undefined {
  return palestrantes.find(
    (p) => p.nome.trim().toLowerCase() === nome.trim().toLowerCase()
  );
}
